sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - autoconf
      - automake
      - autotools-dev
      - bc
      - bison
      - build-essential
      - curl
      - dejagnu
      - expect
      - flex
      - gawk
      - gperf
      - libgmp-dev
      - libmpc-dev
      - libmpfr-dev
      - libtool
      - patchutils
      - texinfo
      - gcc-6
      - g++-6
git:
  quiet: false
before_install:
  - export MAKEFLAGS="-j2"
  - export CXX=g++-6
  - export CC=gcc-6
env:
  - CARGS="--disable-linux  --disable-multilib --with-arch=rv32imcx --with-abi=ilp32"
install: true
script:
  - ./configure --prefix=/tmp/build-default $CARGS
  - travis_wait 90 scripts/wrapper/make_tail
  - travis_wait 180 scripts/wrapper/make_tail check
  - make report
