sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - autoconf
      - automake
      - autotools-dev
      - bc
      - bison
      - build-essential
      - curl
      - dejagnu
      - expect
      - flex
      - gawk
      - gperf
      - libgmp-dev
      - libmpc-dev
      - libmpfr-dev
      - libtool
      - patchutils
      - texinfo
      - gcc-6
      - g++-6
before_install:
  - export MAKEFLAGS="-j3"
  - export CXX=g++-6
  - export CC=gcc-6
env:
#  - CARGS="--enable-linux  --disable-multilib --with-arch=rv32imac --with-abi=ilp32"
#  - CARGS="--enable-linux  --disable-multilib --with-arch=rv32imafdc --with-abi=ilp32"
#  - CARGS="--enable-linux  --disable-multilib --with-arch=rv32imafdc --with-abi=ilp32d"
#  - CARGS="--enable-linux  --disable-multilib --with-arch=rv64imac --with-abi=lp64"
#  - CARGS="--enable-linux  --disable-multilib --with-arch=rv64imafdc --with-abi=lp64"
#  - CARGS="--enable-linux  --disable-multilib --with-arch=rv64imafdc --with-abi=lp64d"
  - CARGS="--disable-linux  --disable-multilib --with-arch=rv32ix --with-abi=ilp32"
  - CARGS="--disable-linux  --disable-multilib --with-arch=rv32imx --with-abi=ilp32"
  - CARGS="--disable-linux  --disable-multilib --with-arch=rv32iacx --with-abi=ilp32"
  - CARGS="--disable-linux  --disable-multilib --with-arch=rv32imacx --with-abi=ilp32"
  - CARGS="--disable-linux  --disable-multilib --with-arch=rv32imafcx --with-abi=ilp32f"
  - CARGS="--disable-linux  --disable-multilib --with-arch=rv64imacx --with-abi=lp64"
  - CARGS="--disable-linux  --disable-multilib --with-arch=rv64imafdcx --with-abi=lp64d"
install: true
script:
  - ./configure --prefix=/tmp/build-default $CARGS
  - travis_wait 90 scripts/wrapper/make_tail
  - travis_wait 180 scripts/wrapper/make_tail check
  - make report
